- name: Get MSSQL ISO if needed
  run_once: true
  block:
    - name: Create /opt/ludus/resources/iso directory if it doesn't exist
      ansible.builtin.file:
        path: "{{ ludus_install_directory }}/resources/iso"
        state: directory
        recurse: true
      delegate_to: localhost

    - name: Check if MSSQL ISO exists
      ansible.builtin.stat:
        path: "{{ ludus_install_directory }}/resources/iso/{{ ludus_mssql_iso_url.split('/') | last }}"
      delegate_to: localhost
      register: mssql_iso_check

    - name: Downloading MSSQL ISO - This will take a while
      ansible.builtin.get_url:
        url: "{{ ludus_mssql_iso_url }}"
        dest: "{{ ludus_install_directory }}/resources/iso/{{ ludus_mssql_iso_url.split('/') | last }}"
        checksum: "{{ ludus_mssql_iso_checksum }}"
        mode: "660"
      delegate_to: localhost
      when: not mssql_iso_check.stat.exists

- name: Check if MSSQL ISO exists on host
  ansible.windows.win_stat:
    path: "{{ ludus_mssql_iso_directory }}\\{{ ludus_mssql_iso_url.split('/') | last }}"
  register: mssql_iso_host_check

- name: Copy MSSQL ISO to windows host
  ansible.windows.win_copy:
    src: "{{ ludus_install_directory }}/resources/iso/{{ ludus_mssql_iso_url.split('/') | last }}"
    dest: "{{ ludus_mssql_iso_directory }}\\{{ ludus_mssql_iso_url.split('/') | last }}"
  when: not mssql_iso_host_check.stat.exists
